apiVersion: v1
kind: Service
metadata:
  name: innovate-service-latest
  namespace: develop
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: innovate-latest
  type: LoadBalancer